### PR TITLE
Sampler script

### PR DESCRIPTION
**Pull request by michaelsilver**
This is a script I wrote a while ago to get some sample results for Siemens. Normally, it just prints the results of a bunch of fetching commands, but its usually nice to pipe it into an output file. Thought it's nice to have around for "sanity check" and also demoing purposes.

### CODE REVIEW

**Comment by alvaromorales** [comment]
Looks good. You might want to sample from other methods such as `articles_of_class`. QuantifiedCode also has some good suggestions, e.g. unnecessary pass.

**Comment by michaelsilver** [comment]
Ok, thanks for the review, @alvaromorales ! Would you mind pushing the additions you made to the script when we were working on it together last week? The timing function is really useful, and I think you might have added samples from other methods if I remember correctly.

After you do that, I will make sure to add whatever methods are still missing, and follow QuantifiedCode's suggestions.

**Comment by alvaromorales** [comment]
Sounds good; just pushed some changes.

**Comment by michaelsilver** [comment]
Fixed basically all QuantifiedCode issues (but I didn't add a docstring to `main()`). With your push, all fetch methods are covered, but I added a couple more hyponym examples for good measure.

Good to go?

**Comment by alvaromorales** [comment]
Looks good!

I'm pretty happy with the code analysis from QuanitifiedCode. As a guideline, I think we should take QC issues as suggestions, and not as merge-blocking bugs.

**Pull request merged**
