### PR TITLE
Parallelize and speed up DB creation

### LINKED ISSUE #5: Fast way to loop through the output of WikiExtractor
Implement a fast way to loop through the output of WikiExtractor, which @alvaromorales  seems to be able to do in Elasticstart indexing. The functions @alvaromorales suggested for me from https://github.com/infolab-csail/elasticstart/blob/master/scripts/index_abstracts.py (`get_header` and `get_abstract`) require me to provide the text and header of the article, which needs to be done in an efficient way. Looks like he is using codecs and some fancy multi-threading. Not sure if all that is necessary for me, but at least it has to be done relatively efficiently. Maybe the easiest thing might be just have Elasticstart call the [`insert()` function](https://github.com/infolab-csail/wikithingsdb/blob/master/wikithingsdb/create.py#L57) in create.py and have it populate the DB? @alvaromorales, what do you think about that?

### PR DESCRIPTION
**Pull request by alvaromorales**
Big changes to make the process of creating WikithingsDB faster. The DB creation completed successfully on nauru. It took about 53 hours for 4.9M Wikipedia articles.

Major changes:
* Handle configuration through environment variables (add this line to your bashrc: `source /data/infolab/misc/elasticstart/elasticstart.env`).
* Partition the large XML file into smaller chunks
* Use multithreading to mitigate the bottleneck of getting types from Whoami
* Use SQLAlchemy's bulk insert features

I used the following command to run the whole thing on nauru: `wikithingsdb -t 12 /scratch/alvarom/data/partitions -l create.log`

See commit messages for more details.

Fixes #5 and #6

### CODE REVIEW

**Comment by sfelshin** [comment]
On Sep 20, 2015, at 5:14 PM, Alvaro Morales wrote:
> Major changes:
> 	� Handle configuration through environment variables (add this line to your bashrc: source /data/infolab/misc/elasticstart/elasticstart.env).
> 	� [snip]
> I used the following command to run the whole thing on nauru: wikithingsdb -t 12 /scratch/alvarom/data/partitions -l create.log

Sounds like this belongs in the WikiThingsDB page in the Infolab wiki ...

**Comment by michaelsilver** [comment]
Awesome, thank you so much! Could you please just add a section to the README with step-by-step instructions on how to create the DB with these new changes? For example, I see that there is now a ` scripts/partition.py` script that I presume needs to be run before `wikithingsdb -t 12 /scratch/alvarom/data/partitions -l create.log`, right? Also, what commands did you use to sucessfully bootstrap `page` and `redirect` from the Wiki dumps?

**Comment by alvaromorales** [comment]
I updated the README.

**Comment by michaelsilver** [comment]
Note for reference: this PR uses bulk inserts now which might explain the bad ordering of hypernyms. See #11 for a discussion of this problem.

**Pull request merged**
